principal/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'principal'

urlpatterns = [
    path('', views.home, name='home'),
    path('home_adm/', views.home_adm, name='home_adm'),    
    # path('imagem-topo/', views.AdicionarImagemTopo, name='imagem_topo'),    
    path('imagem-caurocel1/', views.AdicionarCaroucel1, name='imagem_caurocel1'),    
    path('imagem-caurocel2/', views.AdicionarCaroucel2, name='imagem_caurocel2'),    
    path('imagem-caurocel3/', views.AdicionarCaroucel3, name='imagem_caurocel3'),    
    path('imagem-lateral/', views.AdicionarImagemLateral, name='imagem_lateral'),    
    path('imagem-destaque/', views.AdicionarImagemDestaque, name='imagem_destaque'),    
    path('video/', views.AdicionarVideo, name='video'),    
    path('imagem-tabs-info/', views.AdicionarTabsInfo, name='tabs_info'),    
    path('imagem-tabs-palestra/', views.AdicionarTabsPalestra, name='tabs_palestra'),    
    path('imagem-tabs-contato/', views.AdicionarTabsContato, name='tabs_contato'),    
    path('novocontato/', views.NovoContato, name='novocontato'),    
    # path('ultimos_cadastros/', views.UltimosCadastros, name='ultimos_cadastros'),    
]

site_professor/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('principal.urls')),
    path('accounts/', include('allauth.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/adm/addimagemtopo.html
{% extends 'adm/base_adm.html' %}
{% load static %}
{% load bootstrap4 %}

{% block main %}

<div class="container bg-light gt-4 pt-3 pb-3">
    <div class="row">
                <form method="POST" enctype="multipart/form-data">
                    <b class="text-secundary">Adcionar Imagem Topo</b>
                    <div class="card bg-white mt-2 mb-5">
                        <div class="card-body">
                            {% csrf_token %}
                            {% bootstrap_form form %}
                        </div>
                    </div>
                    <button type="submit" class="btn btn-warning">Salvar Imagem</button>
                </form>
            
        
    </div>
</div>




{% endblock %}

templates/adm/adicionarcaroucel1.html
{% extends 'adm/base_adm.html' %}
{% load static %}
{% load bootstrap4 %}

{% block main %}

<div class="container bg-light gt- pt-3 pb-3">
    <div class="row">
                <form method="POST" enctype="multipart/form-data">
                    <b class="text-secundary">Adcionar Carrossel 1 e Descrições</b>
                    <div class="card bg-white mt-2 mb-5">
                        <div class="card-body">
                            {% csrf_token %}
                            {% bootstrap_form form %}
                        </div>
                    </div>
                    <button type="submit" class="btn btn-warning">Salvar Imagem</button>
                </form>
            
        
    </div>

                
    


</div>


{% endblock %}

}

templates/adm/adicionarcaroucel2.html
{% extends 'adm/base_adm.html' %}
{% load static %}
{% load bootstrap4 %}

{% block main %}

<div class="container bg-light gt- pt-3 pb-">
    <div class="row">
                <form method="POST" enctype="multipart/form-data">
                    <b class="text-secundary">Adcionar Carrossel 2 e Descrições</b>
                    <div class="card bg-white mt-2 mb-5">
                        <div class="card-body">
                            {% csrf_token %}
                            {% bootstrap_form form %}
                        </div>
                    </div>
                    <button type="submit" class="btn btn-warning">Salvar Imagem</button>
                </form>
            
        
    </div>
</div>

{% endblock %}

templates/adm/adicionarcaroucel3.html
{% extends 'adm/base_adm.html' %}
{% load static %}
{% load bootstrap4 %}

{% block main %}

<div class="container bg-light gt- pt-3 pb-3">
    <div class="row">
                <form method="POST" enctype="multipart/form-data">
                    <b class="text-secundary">Adcionar Carrossel 3 e Descrições</b>
                    <div class="card bg-white mt-2 mb-5">
                        <div class="card-body">
                            {% csrf_token %}
                            {% bootstrap_form form %}
                        </div>
                    </div>
                    <button type="submit" class="btn btn-warning">Salvar Imagem</button>
                </form>
            
        
    </div>
</div>

{% endblock %}

templates/adm/adicionarimagemdestaque.html
{% extends 'adm/base_adm.html' %}
{% load static %}
{% load bootstrap4 %}

{% block main %}

<div class="container bg-light gt- pt-3 pb-3">
    <div class="row">
                <form method="POST" enctype="multipart/form-data">
                    <b class="text-secundary">Adcionar Destaque </b>
                    <div class="card bg-white mt-2 mb-5">
                        <div class="card-body">
                            {% csrf_token %}
                            {% bootstrap_form form %}
                        </div>
                    </div>
                    <button type="submit" class="btn btn-warning">Salvar Imagem</button>
                </form>
            
        
    </div>
</div>




{% endblock %}

templates/adm/adicionarimagemlateral.html
{% extends 'adm/base_adm.html' %}
{% load static %}
{% load bootstrap4 %}

{% block main %}

<div class="container bg-light gt- pt-3 pb-3">
    <div class="row">
                <form method="POST" enctype="multipart/form-data">
                    <b class="text-secundary">Adcionar Imagem Lateral</b>
                    <div class="card bg-white mt-2 mb-5">
                        <div class="card-body">
                            {% csrf_token %}
                            {% bootstrap_form form %}
                        </div>
                    </div>
                    <button type="submit" class="btn btn-warning">Salvar Imagem</button>
                </form>
            
        
    </div>
</div>




{% endblock %}

templates/adm/adicionartabscontato.html
{% extends 'adm/base_adm.html' %}
{% load static %}
{% load bootstrap4 %}

{% block main %}

<div class="container bg-light gt- pt-3 pb-3">
    <div class="row">
                <form method="POST" enctype="multipart/form-data">
                    <b class="text-secundary">Adcionar Tabs Contato</b>
                    <div class="card bg-white mt-2 mb-5">
                        <div class="card-body">
                            {% csrf_token %}
                            {% bootstrap_form form %}
                        </div>
                    </div>
                    <button type="submit" class="btn btn-warning">Salvar Imagem</button>
                </form>
            
        
    </div>
</div>




{% endblock %}

templates/adm/adicionartabsinfo.html
{% extends 'adm/base_adm.html' %}
{% load static %}
{% load bootstrap4 %}

{% block main %}

<div class="container bg-light gt- pt-3 pb-3">
    <div class="row">
                <form method="POST" enctype="multipart/form-data">
                    <b class="text-secundary">Adcionar Tabs Info</b>
                    <div class="card bg-white mt-2 mb-5">
                        <div class="card-body">
                            {% csrf_token %}
                            {% bootstrap_form form %}
                        </div>
                    </div>
                    <button type="submit" class="btn btn-warning">Salvar Imagem</button>
                </form>
            
        
    </div>
</div>




{% endblock %}

templates/adm/adicionartabspalestra.html
{% extends 'adm/base_adm.html' %}
{% load static %}
{% load bootstrap4 %}

{% block main %}

<div class="container bg-light gt- pt-3 pb-3">
    <div class="row">
                <form method="POST" enctype="multipart/form-data">
                    <b class="text-secundary">Adcionar Tabs Palestra</b>
                    <div class="card bg-white mt-2 mb-5">
                        <div class="card-body">
                            {% csrf_token %}
                            {% bootstrap_form form %}
                        </div>
                    </div>
                    <button type="submit" class="btn btn-warning">Salvar Imagem</button>
                </form>
            
        
    </div>
</div>




{% endblock %}

templates/adm/adicionarvideo.html
{% extends 'adm/base_adm.html' %}
{% load static %}
{% load bootstrap4 %}

{% block main %}

<div class="container bg-light gt- pt-3 pb-3">
    <div class="row">
                <form method="POST" enctype="multipart/form-data">
                    <b class="text-secundary">Adcionar Vídeo </b>
                    <div class="card bg-white mt-2 mb-5">
                        <div class="card-body">
                            {% csrf_token %}
                            {% bootstrap_form form %}
                        </div>
                    </div>
                    <button type="submit" class="btn btn-warning">Salvar Vídeo</button>
                </form>
            
        
    </div>
</div>




{% endblock %}

templates/adm/base_adm.html
{% load static %}
{% load embed_video_tags %}
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Home{% endblock title %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static '/css/style.css' %}">
</head>
<body>
<div class="container">
    <ul class="nav justify-content-end">
        <!-- <li class="nav-item">
          <a class="nav-link active" href="#">Active</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>-->
        <li class="nav-item">
          <a class="nav-link" href="{% url 'principal:home_adm' %}">Inicial</a>
        </li>                                 
        <li class="nav-item">
            {% if user.is_authenticated %}
                <a href="{% url 'account_logout' %}"class="nav-link">Logout</a>
            {% else %}
                <a href="{% url 'account_login' %}" class="nav-link">Login</a>
            {% endif %}
        </li>
      </ul>   
    </div>


{% block content %}

{% url 'principal:imagem_caurocel1' as imagem_caurocel1_url %}
{% url 'principal:imagem_caurocel2' as imagem_caurocel2_url %}
{% url 'principal:imagem_caurocel3' as imagem_caurocel3_url %}
{% url 'principal:imagem_lateral' as imagem_lateral_url %}
{% url 'principal:imagem_destaque' as imagem_destaque_url %}
{% url 'principal:video' as video_url %}
{% url 'principal:tabs_info' as tabs_info_url %}
{% url 'principal:tabs_palestra' as tabs_palestra_url %}
{% url 'principal:tabs_contato' as tabs_contato_url %}


        <div class="container bg-light gt-4 pt-3 pb-3">
            <div class="row">
                <div class="col-lg-4">
                    <h2><b>Cadastro das imagens e vídeos</b></h2>
                    <div class="list-group mt-5">
                        <a href="{% url 'principal:imagem_caurocel1' %}" class="list-group-item list-group-item-action {% if request.path == imagem_caurocel1_url %}active{% endif %}">Carrossel 1</a>
                        <a href="{% url 'principal:imagem_caurocel2' %}" class="list-group-item list-group-item-action {% if request.path == imagem_caurocel2_url %}active{% endif %}">Carrossel 2</a>
                        <a href="{% url 'principal:imagem_caurocel3' %}" class="list-group-item list-group-item-action {% if request.path == imagem_caurocel3_url %}active{% endif %}">Carrossel 3</a>
                        <a href="{% url 'principal:imagem_lateral' %}" class="list-group-item list-group-item-action {% if request.path == imagem_lateral_url %}active{% endif %}">Imagens lateral</a>
                        <a href="{% url 'principal:imagem_destaque' %}" class="list-group-item list-group-item-action {% if request.path == imagem_destaque_url %}active{% endif %}">Imagens destaque</a>
                        <a href="{% url 'principal:video' %}" class="list-group-item list-group-item-action {% if request.path == video_url %}active{% endif %}">Vídeos</a>
                        <a href="{% url 'principal:tabs_info' %}" class="list-group-item list-group-item-action {% if request.path == tabs_info_url %}active{% endif %}">Tabs info</a>
                        <a href="{% url 'principal:tabs_palestra' %}" class="list-group-item list-group-item-action {% if request.path == tabs_palestra_url %}active{% endif %}">Tabs palestras</a>
                        <a href="{% url 'principal:tabs_contato' %}" class="list-group-item list-group-item-action {% if request.path == tabs_contato_url %}active{% endif %}">Tabs contato</a>
                    </div>



                </div>
                <div class="col-lg-8">
                    {% block main %}
                    
                    {% endblock %}
                </div>

            </div>
        </div>



{% endblock %}



{% block body %}

{% endblock %}
    
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js" integrity="sha384-+sLIOodYLS7CIrQpBjl+C7nPvqq+FbNUBDunl/OZv93DB7Ln/533i8e/mZXLi/P+" crossorigin="anonymous"></script>
</body>
</html>

templates/adm/principal_adm.html
{% extends 'adm/base_adm.html' %}
{% load static %}


{% block main %}
    

{% endblock %}

templates/adm/ultimoscadastros.html
{% extends 'adm/base_adm.html' %}
{% load static %}


{% block main %}
{% for c in carousel10 %}

                   
                    {{ c.decricao_curta }}
                    {{ c.decricao_maior }}
                    <img class="d-block w-50" src="{{ c.carousel1.url }}" height="50" width="10">
                    
                {% endfor %}

{% endblock %}